version: '2'
services:
  flights:
    container_name: traveloo-flights
    build:
      context: traveloo-flights
    expose:
      - 8080
    ports:
      - 8081:8080
  be:
    container_name: traveloo-be
    build:
      context: traveloo-be
    expose:
      - 8080
    ports:
      - 8080:8080