version: '2'
services:
  flights:
    container_name: traveloo-flights
    build:
      context: traveloo-flights
    expose:
      - 8080
    ports:
      - 8081:8080
  be:
    container_name: traveloo-be
    build:
      context: traveloo-be
    expose:
      - 8080
    ports:
      - 8080:8080
    environment:
      - FLIGHTS_LOCATION=http://flights:8080
  fe:
    container_name: traveloo-fe
    build:
      context: traveloo-fe
      args:
        - --no-cache
    expose:
      - 80
    ports:
      - 80:80